# Generated by Django 3.2 on 2021-04-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_eventsideamodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postideamodel',
            name='createdby_id',
        ),
    ]
