# Generated by Django 3.2 on 2021-04-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_postideamodel_createdby_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postideamodel',
            name='createdby_id',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postideamodel',
            name='createdby_image',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
    ]
