# Generated by Django 3.1.7 on 2021-05-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsIdeaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=200)),
                ('EventDate', models.DateField(null=True)),
                ('EventType', models.CharField(max_length=200)),
                ('EventPlace', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('EventLink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendfrom_id', models.IntegerField()),
                ('sendfrom_name', models.CharField(max_length=200)),
                ('sendfrom_img', models.CharField(max_length=200)),
                ('sendto_id', models.IntegerField()),
                ('sendto_name', models.CharField(max_length=200)),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PostIdeaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Img', models.CharField(max_length=200)),
                ('ExceptedPrice', models.IntegerField()),
                ('Progress', models.IntegerField()),
                ('CurrentTeamSize', models.IntegerField()),
                ('InvestorSize', models.IntegerField()),
                ('FundingAmount', models.IntegerField()),
                ('FinancialStatus', models.CharField(max_length=200)),
                ('PatentDetails', models.CharField(max_length=200)),
                ('History', models.CharField(max_length=200)),
                ('createdby_id', models.IntegerField()),
                ('createdby_name', models.CharField(max_length=200)),
                ('createdby_image', models.CharField(max_length=200)),
            ],
        ),
    ]
