# Generated by Django 3.1.7 on 2021-04-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostIdeaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Img', models.CharField(max_length=200)),
                ('Progress', models.IntegerField()),
                ('CurrentTeamSize', models.IntegerField()),
                ('InvestorSize', models.IntegerField()),
                ('FundingAmount', models.IntegerField()),
                ('FinancialStatus', models.CharField(max_length=200)),
                ('PatentDetails', models.IntegerField()),
                ('History', models.CharField(max_length=200)),
                ('createdby_id', models.IntegerField()),
            ],
        ),
    ]
