# Generated by Django 3.1.7 on 2021-05-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postideamodel',
            name='PatentDetails',
            field=models.CharField(max_length=200),
        ),
    ]
