# Generated by Django 3.1.7 on 2021-04-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsIdeaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=200)),
                ('EventDate', models.DateField(null=True)),
                ('EventType', models.CharField(max_length=200)),
                ('EventPlace', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('EventLink', models.CharField(max_length=200)),
            ],
        ),
    ]
