# Generated by Django 3.1.7 on 2021-04-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_postideamodel_createdby_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postideamodel',
            name='createdby_id',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
    ]
