# Generated by Django 3.1.7 on 2021-04-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postideamodel_createdby_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postideamodel',
            name='createdby_image',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
    ]
